baseURL = "https://blog.clay4649.com/"
languageCode = "en-us"
title = "Clay's Blog"
theme = "hugo-bootstrap"

# Code Block
pygmentsCodeFences = true
pygmentsStyle = "monokai"

copyright = " "

# Google analytics
googleAnalytics = "UA-131750785-1"

[languages.en]
  languageName = "English"

  # Replace the default footer message with a localized message
  # copyright = "Hugo template made with ❤ by Xzya"

  [[languages.en.menu.main]]
    url = "/"
    name = "Home"
    weight = 1


[taxonomies]
    tag = "tags"
    category = "categories"

[params]
  # Google AdSense
  googleAdClient = "ca-pub-7613219603223395"